[package]
name = "rbposd"
version = "0.3.0"
edition = "2024"
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.rs/rbposd"
description = "Belief-propagation and ordered-statistics decoding for binary linear codes"
publish = ["crates-io"]
include = [
    "/src/**",
    "/tests/**",
    "/examples/**",
    "/dev/**",
    "/scripts/**",
    "/doc/**",
    "/README.md",
    "/LICENSE",
    "/Cargo.toml",
]

[dependencies]

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
