[package]
name = "rmatching"
version = "0.1.1"
edition = "2024"

[features]
bench = ["dep:rstim", "dep:rand", "dep:serde", "dep:serde_json"]

[dependencies]
rstim = { path = "../rstim", optional = true }
rand = { version = "0.8", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
rstim = { path = "../rstim" }
