//! Experimental coherent active-state evolution for Clifford+T circuits.
//!
//! The shared Clifford tableau represents a unitary frame `U`. A dense vector
//! stores amplitudes of `U|v>` for virtual bit strings `v` generated by a small
//! independent set of active X coordinates. The entries are amplitudes, not
//! probabilities of a classical mixture. Measurement and circuit dispatch are
//! added in later stages of issue #739.

use crate::sim::packed_inverse_tableau::CanonicalTableauSnapshot;
use crate::sim::tableau::StabilizerState;

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct ComplexAmp {
    pub re: f64,
    pub im: f64,
}

impl ComplexAmp {
    pub const fn new(re: f64, im: f64) -> Self {
        Self { re, im }
    }

    pub fn norm_sqr(self) -> f64 {
        self.re * self.re + self.im * self.im
    }

    pub fn conj(self) -> Self {
        Self::new(self.re, -self.im)
    }
}

impl std::ops::Add for ComplexAmp {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        Self::new(self.re + rhs.re, self.im + rhs.im)
    }
}

impl std::ops::Mul for ComplexAmp {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        Self::new(
            self.re * rhs.re - self.im * rhs.im,
            self.re * rhs.im + self.im * rhs.re,
        )
    }
}

impl std::ops::Mul<f64> for ComplexAmp {
    type Output = Self;

    fn mul(self, rhs: f64) -> Self {
        Self::new(self.re * rhs, self.im * rhs)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CliffordGate {
    H(usize),
    S(usize),
    SDag(usize),
    X(usize),
    Y(usize),
    Z(usize),
    CX(usize, usize),
    CZ(usize, usize),
    Swap(usize, usize),
}

#[derive(Clone, Debug)]
pub struct ActiveState {
    num_qubits: usize,
    frame: StabilizerState,
    axes: Vec<Vec<bool>>,
    coefficients: Vec<ComplexAmp>,
    global_phase: ComplexAmp,
    max_active_qubits: usize,
}

impl ActiveState {
    pub fn new(num_qubits: usize, max_active_qubits: usize) -> Self {
        Self {
            num_qubits,
            frame: StabilizerState::new(num_qubits),
            axes: Vec::new(),
            coefficients: vec![ComplexAmp::new(1.0, 0.0)],
            global_phase: ComplexAmp::new(1.0, 0.0),
            max_active_qubits,
        }
    }

    pub fn num_qubits(&self) -> usize {
        self.num_qubits
    }

    pub fn active_rank(&self) -> usize {
        self.axes.len()
    }

    pub fn active_axes(&self) -> &[Vec<bool>] {
        &self.axes
    }

    pub fn coefficients(&self) -> &[ComplexAmp] {
        &self.coefficients
    }

    pub fn global_phase(&self) -> ComplexAmp {
        self.global_phase
    }

    pub fn frame_snapshot(&self) -> CanonicalTableauSnapshot {
        self.frame.canonical_snapshot()
    }

    pub fn apply_clifford(&mut self, gate: CliffordGate) -> Result<(), String> {
        use CliffordGate::*;
        let n = self.num_qubits();
        let check_one = |q: usize| {
            if q < n {
                Ok(())
            } else {
                Err(format!("qubit {q} outside {n}-qubit near-Clifford state"))
            }
        };
        match gate {
            H(q) | S(q) | SDag(q) | X(q) | Y(q) | Z(q) => check_one(q)?,
            CX(a, b) | CZ(a, b) | Swap(a, b) => {
                check_one(a)?;
                check_one(b)?;
                if a == b {
                    return Err("two-qubit Clifford gate requires distinct targets".into());
                }
            }
        }
        match gate {
            H(q) => self.frame.h(q),
            S(q) => self.frame.s(q),
            SDag(q) => self.frame.s_dag(q),
            X(q) => self.frame.x_gate(q),
            Y(q) => self.frame.y_gate(q),
            Z(q) => self.frame.z_gate(q),
            CX(a, b) => self.frame.cx(a, b),
            CZ(a, b) => self.frame.cz(a, b),
            Swap(a, b) => self.frame.swap(a, b),
        }
        Ok(())
    }

    pub fn t(&mut self, q: usize) -> Result<(), String> {
        self.rotate_z(q, false)
    }

    pub fn t_dag(&mut self, q: usize) -> Result<(), String> {
        self.rotate_z(q, true)
    }

    fn rotate_z(&mut self, q: usize, dagger: bool) -> Result<(), String> {
        if q >= self.num_qubits() {
            return Err(format!("qubit {q} outside near-Clifford state"));
        }
        let n = self.num_qubits();
        let mut physical_z = vec![false; n];
        physical_z[q] = true;
        let pauli = self.physical_pauli(&vec![false; n], &physical_z)?;
        let (mask, independent) = self.coordinate_mask(&pauli.x);
        if independent {
            let rank = self.axes.len();
            let expanded_len = self
                .coefficients
                .len()
                .checked_mul(2)
                .ok_or_else(|| "near-Clifford active-state size overflow".to_string())?;
            if rank >= self.max_active_qubits
                || rank >= usize::BITS as usize - 1
                || expanded_len > isize::MAX as usize / size_of::<ComplexAmp>()
            {
                return Err(format!(
                    "near-Clifford active-state limit exceeded at rank {}",
                    rank + 1
                ));
            }
            self.axes.push(pauli.x.clone());
            self.coefficients
                .resize(expanded_len, ComplexAmp::default());
        }
        let mask = if independent {
            self.coefficients.len() / 2
        } else {
            mask
        };
        let old = self.coefficients.clone();
        let mut next = vec![ComplexAmp::default(); old.len()];
        let c = (std::f64::consts::PI / 8.0).cos();
        let s = (std::f64::consts::PI / 8.0).sin();
        let rotation = ComplexAmp::new(0.0, if dagger { s } else { -s });
        for (index, amplitude) in old.iter().copied().enumerate() {
            let virtual_bits = self.virtual_bits(index);
            let sign = if dot(&pauli.z, &virtual_bits) {
                -1.0
            } else {
                1.0
            };
            let image = i_pow(pauli.phase) * (amplitude * sign);
            next[index] = next[index] + amplitude * c;
            next[index ^ mask] = next[index ^ mask] + image * rotation;
        }
        self.coefficients = next;
        let angle = if dagger {
            -std::f64::consts::PI / 8.0
        } else {
            std::f64::consts::PI / 8.0
        };
        self.global_phase = self.global_phase * ComplexAmp::new(angle.cos(), angle.sin());
        Ok(())
    }

    fn virtual_bits(&self, index: usize) -> Vec<bool> {
        let mut bits = vec![false; self.num_qubits()];
        for (axis_index, axis) in self.axes.iter().enumerate() {
            if index & (1 << axis_index) != 0 {
                xor(&mut bits, axis);
            }
        }
        bits
    }

    fn coordinate_mask(&self, x: &[bool]) -> (usize, bool) {
        let n = x.len();
        let mut pivots: Vec<Option<(Vec<bool>, usize)>> = vec![None; n];
        for (index, axis) in self.axes.iter().enumerate() {
            let mut row = axis.clone();
            let mut mask = 1 << index;
            while let Some(pivot) = row.iter().position(|&value| value) {
                if let Some((basis_row, basis_mask)) = &pivots[pivot] {
                    xor(&mut row, basis_row);
                    mask ^= basis_mask;
                } else {
                    pivots[pivot] = Some((row, mask));
                    break;
                }
            }
        }
        let mut row = x.to_vec();
        let mut mask = 0;
        while let Some(pivot) = row.iter().position(|&value| value) {
            if let Some((basis_row, basis_mask)) = &pivots[pivot] {
                xor(&mut row, basis_row);
                mask ^= basis_mask;
            } else {
                return (0, true);
            }
        }
        (mask, false)
    }

    fn physical_pauli(&self, physical_x: &[bool], physical_z: &[bool]) -> Result<Pauli, String> {
        let snapshot = self.frame.canonical_snapshot();
        let n = snapshot.num_qubits;
        let mut virtual_x = vec![false; n];
        let mut virtual_z = vec![false; n];
        for i in 0..n {
            virtual_x[i] =
                dot(physical_x, &snapshot.z[n + i]) ^ dot(physical_z, &snapshot.x[n + i]);
            virtual_z[i] = dot(physical_x, &snapshot.z[i]) ^ dot(physical_z, &snapshot.x[i]);
        }
        let mut product = Pauli::identity(n);
        for (i, &selected) in virtual_x.iter().enumerate() {
            if selected {
                product.multiply(&Pauli::from_snapshot_row(&snapshot, i));
            }
        }
        for (i, &selected) in virtual_z.iter().enumerate() {
            if selected {
                product.multiply(&Pauli::from_snapshot_row(&snapshot, n + i));
            }
        }
        if product.x != physical_x || product.z != physical_z {
            return Err("Clifford frame failed to reconstruct physical Pauli".into());
        }
        let desired_phase = (physical_x
            .iter()
            .zip(physical_z)
            .filter(|(x, z)| **x && **z)
            .count()
            % 4) as u8;
        let phase = (desired_phase + 4 - product.phase) % 4;
        Ok(Pauli {
            x: virtual_x,
            z: virtual_z,
            phase,
        })
    }
}

#[derive(Clone)]
struct Pauli {
    x: Vec<bool>,
    z: Vec<bool>,
    /// Exponent of `i` in `i^phase X^x Z^z`.
    phase: u8,
}

impl Pauli {
    fn identity(n: usize) -> Self {
        Self {
            x: vec![false; n],
            z: vec![false; n],
            phase: 0,
        }
    }

    fn from_snapshot_row(snapshot: &CanonicalTableauSnapshot, row: usize) -> Self {
        let y_count = snapshot.x[row]
            .iter()
            .zip(&snapshot.z[row])
            .filter(|(x, z)| **x && **z)
            .count();
        Self {
            x: snapshot.x[row].clone(),
            z: snapshot.z[row].clone(),
            phase: (snapshot.phase[row] + (y_count % 4) as u8) % 4,
        }
    }

    fn multiply(&mut self, rhs: &Pauli) {
        let sign = if dot(&self.z, &rhs.x) { 2 } else { 0 };
        self.phase = (self.phase + rhs.phase + sign) % 4;
        xor(&mut self.x, &rhs.x);
        xor(&mut self.z, &rhs.z);
    }
}

fn dot(a: &[bool], b: &[bool]) -> bool {
    a.iter().zip(b).filter(|(x, y)| **x && **y).count() & 1 == 1
}

fn xor(a: &mut [bool], b: &[bool]) {
    for (left, right) in a.iter_mut().zip(b) {
        *left ^= *right;
    }
}

fn i_pow(exponent: u8) -> ComplexAmp {
    match exponent % 4 {
        0 => ComplexAmp::new(1.0, 0.0),
        1 => ComplexAmp::new(0.0, 1.0),
        2 => ComplexAmp::new(-1.0, 0.0),
        _ => ComplexAmp::new(0.0, -1.0),
    }
}
