//! Experimental coherent active-state evolution for Clifford+T circuits.
//!
//! The shared Clifford tableau represents a unitary frame `U`. A dense vector
//! stores amplitudes of `U|v>` for virtual bit strings `v` generated by a small
//! independent set of active X coordinates. The entries are amplitudes, not
//! probabilities of a classical mixture. The opt-in circuit runner also handles
//! supported Pauli noise, classical feedback, and measurement annotations.

use crate::ir::{StimInstr, StimTarget};
use crate::sim::packed_inverse_tableau::CanonicalTableauSnapshot;
use crate::sim::tableau::StabilizerState;
use rand::Rng;

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct ComplexAmp {
    pub re: f64,
    pub im: f64,
}

impl ComplexAmp {
    pub const fn new(re: f64, im: f64) -> Self {
        Self { re, im }
    }

    pub fn norm_sqr(self) -> f64 {
        self.re * self.re + self.im * self.im
    }

    pub fn conj(self) -> Self {
        Self::new(self.re, -self.im)
    }
}

impl std::ops::Add for ComplexAmp {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        Self::new(self.re + rhs.re, self.im + rhs.im)
    }
}

impl std::ops::Mul for ComplexAmp {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self {
        Self::new(
            self.re * rhs.re - self.im * rhs.im,
            self.re * rhs.im + self.im * rhs.re,
        )
    }
}

impl std::ops::Mul<f64> for ComplexAmp {
    type Output = Self;

    fn mul(self, rhs: f64) -> Self {
        Self::new(self.re * rhs, self.im * rhs)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CliffordGate {
    H(usize),
    S(usize),
    SDag(usize),
    X(usize),
    Y(usize),
    Z(usize),
    CX(usize, usize),
    CZ(usize, usize),
    Swap(usize, usize),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MeasurementBasis {
    X,
    Y,
    Z,
}

#[derive(Clone, Debug)]
pub struct ActiveState {
    num_qubits: usize,
    frame: StabilizerState,
    origin: Vec<bool>,
    axes: Vec<Vec<bool>>,
    coefficients: Vec<ComplexAmp>,
    global_phase: ComplexAmp,
    max_active_qubits: usize,
}

impl ActiveState {
    pub fn new(num_qubits: usize, max_active_qubits: usize) -> Self {
        Self {
            num_qubits,
            frame: StabilizerState::new(num_qubits),
            origin: vec![false; num_qubits],
            axes: Vec::new(),
            coefficients: vec![ComplexAmp::new(1.0, 0.0)],
            global_phase: ComplexAmp::new(1.0, 0.0),
            max_active_qubits,
        }
    }

    pub fn num_qubits(&self) -> usize {
        self.num_qubits
    }

    pub fn active_rank(&self) -> usize {
        self.axes.len()
    }

    pub fn active_axes(&self) -> &[Vec<bool>] {
        &self.axes
    }

    /// Virtual basis bit string underlying coordinate zero.
    pub fn origin(&self) -> &[bool] {
        &self.origin
    }

    pub fn coefficients(&self) -> &[ComplexAmp] {
        &self.coefficients
    }

    pub fn global_phase(&self) -> ComplexAmp {
        self.global_phase
    }

    pub fn frame_snapshot(&self) -> CanonicalTableauSnapshot {
        self.frame.canonical_snapshot()
    }

    pub fn apply_clifford(&mut self, gate: CliffordGate) -> Result<(), String> {
        use CliffordGate::*;
        let n = self.num_qubits();
        let check_one = |q: usize| {
            if q < n {
                Ok(())
            } else {
                Err(format!("qubit {q} outside {n}-qubit near-Clifford state"))
            }
        };
        match gate {
            H(q) | S(q) | SDag(q) | X(q) | Y(q) | Z(q) => check_one(q)?,
            CX(a, b) | CZ(a, b) | Swap(a, b) => {
                check_one(a)?;
                check_one(b)?;
                if a == b {
                    return Err("two-qubit Clifford gate requires distinct targets".into());
                }
            }
        }
        match gate {
            H(q) => self.frame.h(q),
            S(q) => self.frame.s(q),
            SDag(q) => self.frame.s_dag(q),
            X(q) => self.frame.x_gate(q),
            Y(q) => self.frame.y_gate(q),
            Z(q) => self.frame.z_gate(q),
            CX(a, b) => self.frame.cx(a, b),
            CZ(a, b) => self.frame.cz(a, b),
            Swap(a, b) => self.frame.swap(a, b),
        }
        Ok(())
    }

    pub fn t(&mut self, q: usize) -> Result<(), String> {
        self.rotate_z(q, false)
    }

    pub fn t_dag(&mut self, q: usize) -> Result<(), String> {
        self.rotate_z(q, true)
    }

    fn rotate_z(&mut self, q: usize, dagger: bool) -> Result<(), String> {
        if q >= self.num_qubits() {
            return Err(format!("qubit {q} outside near-Clifford state"));
        }
        let n = self.num_qubits();
        let mut physical_z = vec![false; n];
        physical_z[q] = true;
        let pauli = self.physical_pauli(&vec![false; n], &physical_z)?;
        let mask = self.ensure_axis(&pauli.x)?;
        let old = self.coefficients.clone();
        let mut next = vec![ComplexAmp::default(); old.len()];
        let c = (std::f64::consts::PI / 8.0).cos();
        let s = (std::f64::consts::PI / 8.0).sin();
        let rotation = ComplexAmp::new(0.0, if dagger { s } else { -s });
        for (index, amplitude) in old.iter().copied().enumerate() {
            let virtual_bits = self.virtual_bits(index);
            let sign = if dot(&pauli.z, &virtual_bits) {
                -1.0
            } else {
                1.0
            };
            let image = i_pow(pauli.phase) * (amplitude * sign);
            next[index] = next[index] + amplitude * c;
            next[index ^ mask] = next[index ^ mask] + image * rotation;
        }
        self.coefficients = next;
        let angle = if dagger {
            -std::f64::consts::PI / 8.0
        } else {
            std::f64::consts::PI / 8.0
        };
        self.global_phase = self.global_phase * ComplexAmp::new(angle.cos(), angle.sin());
        Ok(())
    }

    /// Born probabilities for the two outcomes, without changing the state.
    pub fn measurement_probabilities(
        &self,
        q: usize,
        basis: MeasurementBasis,
    ) -> Result<(f64, f64), String> {
        let pauli = self.single_qubit_pauli(q, basis)?;
        let (mask, independent) = self.coordinate_mask(&pauli.x);
        let expectation = if independent {
            0.0
        } else {
            self.coefficients
                .iter()
                .enumerate()
                .map(|(index, amplitude)| {
                    let virtual_bits = self.virtual_bits(index);
                    let sign = if dot(&pauli.z, &virtual_bits) {
                        -1.0
                    } else {
                        1.0
                    };
                    let image = i_pow(pauli.phase) * (*amplitude * sign);
                    let conjugate = self.coefficients[index ^ mask].conj();
                    (conjugate * image).re
                })
                .sum::<f64>()
        };
        let zero = ((1.0 + expectation) / 2.0).clamp(0.0, 1.0);
        Ok((zero, 1.0 - zero))
    }

    /// Samples and collapses a Pauli-basis measurement. `true` is the -1 outcome.
    pub fn measure(
        &mut self,
        q: usize,
        basis: MeasurementBasis,
        rng: &mut impl Rng,
    ) -> Result<bool, String> {
        if q >= self.num_qubits() {
            return Err(format!("qubit {q} outside near-Clifford state"));
        }
        if self.axes.is_empty() {
            self.rebase_origin_into_frame();
            let outcome = match basis {
                MeasurementBasis::Z => self.frame.measure_z(q, rng).0,
                MeasurementBasis::X => {
                    self.frame.h(q);
                    let bit = self.frame.measure_z(q, rng).0;
                    self.frame.h(q);
                    bit
                }
                MeasurementBasis::Y => {
                    self.frame.s_dag(q);
                    self.frame.h(q);
                    let bit = self.frame.measure_z(q, rng).0;
                    self.frame.h(q);
                    self.frame.s(q);
                    bit
                }
            };
            return Ok(outcome != 0);
        }
        let pauli = self.single_qubit_pauli(q, basis)?;
        let (probability_zero, _) = self.measurement_probabilities(q, basis)?;
        let mask = self.ensure_axis(&pauli.x)?;
        let outcome = rng.r#gen::<f64>() >= probability_zero;
        self.collapse_pauli_measurement(&pauli, mask, outcome)?;
        Ok(outcome)
    }

    fn collapse_pauli_measurement(
        &mut self,
        pauli: &Pauli,
        mask: usize,
        outcome: bool,
    ) -> Result<(), String> {
        let eigenvalue = if outcome { -1.0 } else { 1.0 };
        let old = self.coefficients.clone();
        let mut next = vec![ComplexAmp::default(); old.len()];
        for (index, amplitude) in old.iter().copied().enumerate() {
            let virtual_bits = self.virtual_bits(index);
            let sign = if dot(&pauli.z, &virtual_bits) {
                -1.0
            } else {
                1.0
            };
            let image = i_pow(pauli.phase) * (amplitude * (sign * eigenvalue));
            next[index] = next[index] + amplitude * 0.5;
            next[index ^ mask] = next[index ^ mask] + image * 0.5;
        }
        let norm = next
            .iter()
            .map(|amplitude| amplitude.norm_sqr())
            .sum::<f64>()
            .sqrt();
        if norm <= 1e-15 {
            return Err("near-Clifford measurement selected zero-probability outcome".into());
        }
        for amplitude in &mut next {
            *amplitude = *amplitude * (1.0 / norm);
        }
        self.coefficients = next;
        Ok(())
    }

    fn rebase_origin_into_frame(&mut self) {
        if !self.origin.contains(&true) {
            return;
        }
        let snapshot = self.frame.canonical_snapshot();
        for (q, bit) in self.origin.iter_mut().enumerate() {
            if *bit {
                // U X_q |0> = (U X_q U†) U |0>. Apply that physical Pauli
                // to the frame so the virtual origin returns to zero.
                let pauli = Pauli::from_snapshot_row(&snapshot, q);
                let y_count = pauli
                    .x
                    .iter()
                    .zip(&pauli.z)
                    .filter(|(x, z)| **x && **z)
                    .count() as u8;
                self.global_phase = self.global_phase * i_pow((pauli.phase + 4 - y_count % 4) % 4);
                for (physical_q, (&x, &z)) in pauli.x.iter().zip(&pauli.z).enumerate() {
                    match (x, z) {
                        (true, true) => self.frame.y_gate(physical_q),
                        (true, false) => self.frame.x_gate(physical_q),
                        (false, true) => self.frame.z_gate(physical_q),
                        (false, false) => {}
                    }
                }
                *bit = false;
            }
        }
    }

    /// Measures and prepares the +1 eigenstate of the requested basis.
    /// The returned bit is the measurement result before the reset correction.
    pub fn measure_reset(
        &mut self,
        q: usize,
        basis: MeasurementBasis,
        rng: &mut impl Rng,
    ) -> Result<bool, String> {
        let outcome = self.measure(q, basis, rng)?;
        if outcome {
            let correction = match basis {
                MeasurementBasis::Z => CliffordGate::X(q),
                MeasurementBasis::X | MeasurementBasis::Y => CliffordGate::Z(q),
            };
            self.apply_clifford(correction)?;
        }
        self.retire_fixed_axes();
        Ok(outcome)
    }

    pub fn reset(
        &mut self,
        q: usize,
        basis: MeasurementBasis,
        rng: &mut impl Rng,
    ) -> Result<(), String> {
        self.measure_reset(q, basis, rng).map(|_| ())
    }

    /// Removes active axes whose entire unused half has zero amplitude.
    /// Measurement can fix a virtual computational bit; its value moves into
    /// `origin`, keeping the represented physical state unchanged.
    pub fn retire_fixed_axes(&mut self) -> usize {
        let mut retired = 0;
        let mut axis_index = 0;
        while axis_index < self.axes.len() {
            let mut half_norm = [0.0, 0.0];
            for (index, coefficient) in self.coefficients.iter().enumerate() {
                half_norm[(index >> axis_index) & 1] += coefficient.norm_sqr();
            }
            let fixed = if half_norm[0] < 1e-24 && half_norm[1] > 1e-24 {
                Some(1)
            } else if half_norm[1] < 1e-24 && half_norm[0] > 1e-24 {
                Some(0)
            } else {
                None
            };
            if let Some(fixed) = fixed {
                let axis = self.axes.remove(axis_index);
                if fixed == 1 {
                    xor(&mut self.origin, &axis);
                }
                let low_mask = (1 << axis_index) - 1;
                let reduced_len = self.coefficients.len() / 2;
                let reduced = (0..reduced_len)
                    .map(|index| {
                        let old_index =
                            (index & low_mask) | (fixed << axis_index) | ((index & !low_mask) << 1);
                        self.coefficients[old_index]
                    })
                    .collect();
                self.coefficients = reduced;
                retired += 1;
            } else {
                axis_index += 1;
            }
        }
        retired
    }

    fn single_qubit_pauli(&self, q: usize, basis: MeasurementBasis) -> Result<Pauli, String> {
        let n = self.num_qubits();
        if q >= n {
            return Err(format!("qubit {q} outside near-Clifford state"));
        }
        let mut x = vec![false; n];
        let mut z = vec![false; n];
        x[q] = matches!(basis, MeasurementBasis::X | MeasurementBasis::Y);
        z[q] = matches!(basis, MeasurementBasis::Y | MeasurementBasis::Z);
        self.physical_pauli(&x, &z)
    }

    fn ensure_axis(&mut self, x: &[bool]) -> Result<usize, String> {
        let (mask, independent) = self.coordinate_mask(x);
        if !independent {
            return Ok(mask);
        }
        let rank = self.axes.len();
        let expanded_len = self
            .coefficients
            .len()
            .checked_mul(2)
            .ok_or_else(|| "near-Clifford active-state size overflow".to_string())?;
        if rank >= self.max_active_qubits
            || rank >= usize::BITS as usize - 1
            || expanded_len > isize::MAX as usize / size_of::<ComplexAmp>()
        {
            return Err(format!(
                "near-Clifford active-state limit exceeded at rank {}",
                rank + 1
            ));
        }
        self.axes.push(x.to_vec());
        self.coefficients
            .resize(expanded_len, ComplexAmp::default());
        Ok(expanded_len / 2)
    }

    fn virtual_bits(&self, index: usize) -> Vec<bool> {
        let mut bits = self.origin.clone();
        for (axis_index, axis) in self.axes.iter().enumerate() {
            if index & (1 << axis_index) != 0 {
                xor(&mut bits, axis);
            }
        }
        bits
    }

    fn coordinate_mask(&self, x: &[bool]) -> (usize, bool) {
        let n = x.len();
        let mut pivots: Vec<Option<(Vec<bool>, usize)>> = vec![None; n];
        for (index, axis) in self.axes.iter().enumerate() {
            let mut row = axis.clone();
            let mut mask = 1 << index;
            while let Some(pivot) = row.iter().position(|&value| value) {
                if let Some((basis_row, basis_mask)) = &pivots[pivot] {
                    xor(&mut row, basis_row);
                    mask ^= basis_mask;
                } else {
                    pivots[pivot] = Some((row, mask));
                    break;
                }
            }
        }
        let mut row = x.to_vec();
        let mut mask = 0;
        while let Some(pivot) = row.iter().position(|&value| value) {
            if let Some((basis_row, basis_mask)) = &pivots[pivot] {
                xor(&mut row, basis_row);
                mask ^= basis_mask;
            } else {
                return (0, true);
            }
        }
        (mask, false)
    }

    fn physical_pauli(&self, physical_x: &[bool], physical_z: &[bool]) -> Result<Pauli, String> {
        let snapshot = self.frame.canonical_snapshot();
        let n = snapshot.num_qubits;
        let mut virtual_x = vec![false; n];
        let mut virtual_z = vec![false; n];
        for i in 0..n {
            virtual_x[i] =
                dot(physical_x, &snapshot.z[n + i]) ^ dot(physical_z, &snapshot.x[n + i]);
            virtual_z[i] = dot(physical_x, &snapshot.z[i]) ^ dot(physical_z, &snapshot.x[i]);
        }
        let mut product = Pauli::identity(n);
        for (i, &selected) in virtual_x.iter().enumerate() {
            if selected {
                product.multiply(&Pauli::from_snapshot_row(&snapshot, i));
            }
        }
        for (i, &selected) in virtual_z.iter().enumerate() {
            if selected {
                product.multiply(&Pauli::from_snapshot_row(&snapshot, n + i));
            }
        }
        if product.x != physical_x || product.z != physical_z {
            return Err("Clifford frame failed to reconstruct physical Pauli".into());
        }
        let desired_phase = (physical_x
            .iter()
            .zip(physical_z)
            .filter(|(x, z)| **x && **z)
            .count()
            % 4) as u8;
        let phase = (desired_phase + 4 - product.phase) % 4;
        Ok(Pauli {
            x: virtual_x,
            z: virtual_z,
            phase,
        })
    }
}

#[derive(Clone)]
struct Pauli {
    x: Vec<bool>,
    z: Vec<bool>,
    /// Exponent of `i` in `i^phase X^x Z^z`.
    phase: u8,
}

impl Pauli {
    fn identity(n: usize) -> Self {
        Self {
            x: vec![false; n],
            z: vec![false; n],
            phase: 0,
        }
    }

    fn from_snapshot_row(snapshot: &CanonicalTableauSnapshot, row: usize) -> Self {
        let y_count = snapshot.x[row]
            .iter()
            .zip(&snapshot.z[row])
            .filter(|(x, z)| **x && **z)
            .count();
        Self {
            x: snapshot.x[row].clone(),
            z: snapshot.z[row].clone(),
            phase: (snapshot.phase[row] + (y_count % 4) as u8) % 4,
        }
    }

    fn multiply(&mut self, rhs: &Pauli) {
        let sign = if dot(&self.z, &rhs.x) { 2 } else { 0 };
        self.phase = (self.phase + rhs.phase + sign) % 4;
        xor(&mut self.x, &rhs.x);
        xor(&mut self.z, &rhs.z);
    }
}

fn dot(a: &[bool], b: &[bool]) -> bool {
    a.iter().zip(b).filter(|(x, y)| **x && **y).count() & 1 == 1
}

fn xor(a: &mut [bool], b: &[bool]) {
    for (left, right) in a.iter_mut().zip(b) {
        *left ^= *right;
    }
}

fn i_pow(exponent: u8) -> ComplexAmp {
    match exponent % 4 {
        0 => ComplexAmp::new(1.0, 0.0),
        1 => ComplexAmp::new(0.0, 1.0),
        2 => ComplexAmp::new(-1.0, 0.0),
        _ => ComplexAmp::new(0.0, -1.0),
    }
}

/// Opt-in circuit runner for the currently supported near-Clifford operations.
///
/// The pure-Clifford `Executor` and compiled samplers are unaffected. This
/// experimental runner validates the full instruction tree before execution.
#[derive(Clone, Debug)]
pub struct NearCliffordExecutor {
    instructions: Vec<StimInstr>,
    num_qubits: usize,
    max_active_qubits: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NearCliffordShot {
    pub measurements: Vec<bool>,
    pub detectors: Vec<bool>,
    /// Observable include events in circuit order; repeated indices are not folded.
    pub observables: Vec<(u32, bool)>,
}

const MAX_NEAR_CLIFFORD_QUBITS: usize = 4096;

impl NearCliffordExecutor {
    /// Compiles with a default active-rank limit of 16.
    pub fn compile(instructions: Vec<StimInstr>) -> Result<Self, String> {
        Self::compile_with_limit(instructions, 16)
    }

    pub fn compile_text(text: &str) -> Result<Self, String> {
        Self::compile(crate::parser::parse_lines(text)?)
    }

    pub fn compile_with_limit(
        instructions: Vec<StimInstr>,
        max_active_qubits: usize,
    ) -> Result<Self, String> {
        let mut max_qubit = None;
        validate_near_block(&instructions, &mut max_qubit, &mut 0)?;
        let num_qubits = max_qubit
            .map(|q| {
                usize::try_from(q)
                    .ok()
                    .and_then(|q| q.checked_add(1))
                    .ok_or_else(|| {
                        "near-Clifford qubit index exceeds platform capacity".to_string()
                    })
            })
            .transpose()?
            .unwrap_or(0);
        if num_qubits > MAX_NEAR_CLIFFORD_QUBITS {
            return Err(format!(
                "near-Clifford circuit exceeds {MAX_NEAR_CLIFFORD_QUBITS} physical qubits"
            ));
        }
        Ok(Self {
            instructions,
            num_qubits,
            max_active_qubits,
        })
    }

    pub fn run(&self, rng: &mut impl Rng) -> Result<NearCliffordShot, String> {
        self.run_with_sweep(&[], rng)
    }

    /// Runs one shot with explicit `sweep[k]` inputs. Missing bits default to zero.
    pub fn run_with_sweep(
        &self,
        sweep_bits: &[bool],
        rng: &mut impl Rng,
    ) -> Result<NearCliffordShot, String> {
        let mut state = ActiveState::new(self.num_qubits, self.max_active_qubits);
        let mut measurements = Vec::new();
        let mut detectors = Vec::new();
        let mut observables = Vec::new();
        run_near_block(
            &self.instructions,
            &mut state,
            &mut measurements,
            &mut detectors,
            &mut observables,
            sweep_bits,
            rng,
        )?;
        Ok(NearCliffordShot {
            measurements,
            detectors,
            observables,
        })
    }

    pub fn sample(
        &self,
        shots: usize,
        rng: &mut impl Rng,
    ) -> Result<Vec<NearCliffordShot>, String> {
        self.sample_with_sweep(shots, &[], rng)
    }

    pub fn sample_with_sweep(
        &self,
        shots: usize,
        sweep_bits: &[bool],
        rng: &mut impl Rng,
    ) -> Result<Vec<NearCliffordShot>, String> {
        if shots < 64 {
            return (0..shots)
                .map(|_| self.run_with_sweep(sweep_bits, rng))
                .collect();
        }

        let prefix_len = self
            .instructions
            .iter()
            .take_while(|instruction| is_deterministic_near_instruction(instruction))
            .count();
        if prefix_len == 0 {
            return (0..shots)
                .map(|_| self.run_with_sweep(sweep_bits, rng))
                .collect();
        }

        let mut prepared = ActiveState::new(self.num_qubits, self.max_active_qubits);
        run_near_block(
            &self.instructions[..prefix_len],
            &mut prepared,
            &mut Vec::new(),
            &mut Vec::new(),
            &mut Vec::new(),
            sweep_bits,
            rng,
        )?;

        if self.num_qubits <= 64
            && let [StimInstr::Op { name, targets, .. }] = &self.instructions[prefix_len..]
            && matches!(name.as_str(), "M" | "MZ" | "MX" | "MY")
            && !targets.is_empty()
            && targets
                .iter()
                .all(|target| matches!(target, StimTarget::Qubit(_) | StimTarget::QubitInv(_)))
        {
            let basis = match name.as_str() {
                "MX" => MeasurementBasis::X,
                "MY" => MeasurementBasis::Y,
                _ => MeasurementBasis::Z,
            };
            return sample_cached_terminal_measurements(prepared, targets, basis, shots, rng);
        }

        (0..shots)
            .map(|_| {
                let mut state = prepared.clone();
                let mut measurements = Vec::new();
                let mut detectors = Vec::new();
                let mut observables = Vec::new();
                run_near_block(
                    &self.instructions[prefix_len..],
                    &mut state,
                    &mut measurements,
                    &mut detectors,
                    &mut observables,
                    sweep_bits,
                    rng,
                )?;
                Ok(NearCliffordShot {
                    measurements,
                    detectors,
                    observables,
                })
            })
            .collect()
    }
}

struct TerminalMeasurementNode {
    state: ActiveState,
    measurement: Option<(f64, Pauli, usize)>,
    children: [Option<Box<TerminalMeasurementNode>>; 2],
}

impl TerminalMeasurementNode {
    fn new(state: ActiveState) -> Self {
        Self {
            state,
            measurement: None,
            children: [None, None],
        }
    }
}

fn sample_cached_terminal_measurements(
    prepared: ActiveState,
    targets: &[StimTarget],
    basis: MeasurementBasis,
    shots: usize,
    rng: &mut impl Rng,
) -> Result<Vec<NearCliffordShot>, String> {
    // Bound the cache to at most 2^9 branches. Later measurements continue
    // through the ordinary sampler from the cached collapsed state.
    let cached_depth = targets.len().min(9);
    let mut root = TerminalMeasurementNode::new(prepared);
    let mut results = Vec::with_capacity(shots);
    for _ in 0..shots {
        let mut node = &mut root;
        let mut measurements = Vec::with_capacity(targets.len());
        let mut depth = 0;
        while depth < cached_depth
            && !node.state.axes.is_empty()
            && node.state.coefficients.len() <= 1024
        {
            let q = targets[depth].qubit_index().unwrap() as usize;
            if node.measurement.is_none() {
                let (probability_zero, _) = node.state.measurement_probabilities(q, basis)?;
                let pauli = node.state.single_qubit_pauli(q, basis)?;
                // Match measure(): a rank-limit error happens before the RNG draw.
                let mask = node.state.ensure_axis(&pauli.x)?;
                node.measurement = Some((probability_zero, pauli, mask));
            }
            let (probability_zero, pauli, mask) = node.measurement.as_ref().unwrap();
            let outcome = rng.r#gen::<f64>() >= *probability_zero;
            let branch = usize::from(outcome);
            if node.children[branch].is_none() {
                let mut state = node.state.clone();
                state.collapse_pauli_measurement(pauli, *mask, outcome)?;
                state.retire_fixed_axes();
                node.children[branch] = Some(Box::new(TerminalMeasurementNode::new(state)));
            }
            measurements.push(outcome ^ matches!(targets[depth], StimTarget::QubitInv(_)));
            node = node.children[branch].as_mut().unwrap();
            depth += 1;
        }
        let mut state = node.state.clone();
        for target in &targets[depth..] {
            let q = target.qubit_index().unwrap() as usize;
            let outcome = state.measure(q, basis, rng)?;
            state.retire_fixed_axes();
            measurements.push(outcome ^ matches!(target, StimTarget::QubitInv(_)));
        }
        results.push(NearCliffordShot {
            measurements,
            detectors: Vec::new(),
            observables: Vec::new(),
        });
    }
    Ok(results)
}

// Only these instructions are independent of both the RNG and sweep inputs.
// A REPEAT remains a boundary so its nested instruction tree needs no separate
// classification or partial unrolling.
fn is_deterministic_near_instruction(instruction: &StimInstr) -> bool {
    let StimInstr::Op { name, targets, .. } = instruction else {
        return false;
    };
    match name.as_str() {
        "I" | "H" | "S" | "SQRT_Z" | "S_DAG" | "SQRT_Z_DAG" | "X" | "Y" | "Z" | "T" | "T_DAG"
        | "TICK" | "QUBIT_COORDS" | "SHIFT_COORDS" => true,
        "CX" | "CNOT" | "ZCX" | "CY" | "ZCY" | "CZ" | "ZCZ" | "SWAP" => targets
            .iter()
            .all(|target| matches!(target, StimTarget::Qubit(_))),
        _ => false,
    }
}

fn validate_near_block(
    instructions: &[StimInstr],
    max_qubit: &mut Option<u32>,
    records: &mut u64,
) -> Result<(), String> {
    for instruction in instructions {
        match instruction {
            StimInstr::Repeat { count, body } => {
                if *count == 0 {
                    return Err("near-Clifford REPEAT count must be positive".into());
                }
                let before = *records;
                validate_near_block(body, max_qubit, records)?;
                let per_iteration = *records - before;
                *records = per_iteration
                    .checked_mul(*count)
                    .and_then(|total| before.checked_add(total))
                    .ok_or("near-Clifford measurement record count overflow")?;
            }
            StimInstr::Op {
                name,
                args,
                targets,
                ..
            } => {
                let gate = name.as_str();
                let single = matches!(
                    gate,
                    "I" | "H"
                        | "S"
                        | "SQRT_Z"
                        | "S_DAG"
                        | "SQRT_Z_DAG"
                        | "X"
                        | "Y"
                        | "Z"
                        | "T"
                        | "T_DAG"
                        | "R"
                        | "RZ"
                        | "RX"
                        | "RY"
                );
                let pair = matches!(
                    gate,
                    "CX" | "CNOT" | "ZCX" | "CY" | "ZCY" | "CZ" | "ZCZ" | "SWAP"
                );
                let measure = matches!(
                    gate,
                    "M" | "MZ" | "MX" | "MY" | "MR" | "MRZ" | "MRX" | "MRY"
                );
                let noise_single =
                    matches!(gate, "X_ERROR" | "Y_ERROR" | "Z_ERROR" | "DEPOLARIZE1");
                let noise_pair = gate == "DEPOLARIZE2";
                let annotation = matches!(
                    gate,
                    "DETECTOR" | "OBSERVABLE_INCLUDE" | "TICK" | "QUBIT_COORDS" | "SHIFT_COORDS"
                );
                if !(single || pair || measure || noise_single || noise_pair || annotation) {
                    return Err(format!("near-Clifford unsupported gate {name}"));
                }
                if noise_single || noise_pair {
                    if args.len() != 1 || !args[0].is_finite() || !(0.0..=1.0).contains(&args[0]) {
                        return Err(format!(
                            "near-Clifford {name} requires one probability in [0,1]"
                        ));
                    }
                } else if gate == "OBSERVABLE_INCLUDE" {
                    if args.len() != 1
                        || !args[0].is_finite()
                        || args[0].fract() != 0.0
                        || args[0] < 0.0
                        || args[0] > u32::MAX as f64
                    {
                        return Err("near-Clifford OBSERVABLE_INCLUDE requires one nonnegative integer index".into());
                    }
                } else if matches!(gate, "DETECTOR" | "QUBIT_COORDS" | "SHIFT_COORDS") {
                    if args.iter().any(|value| !value.is_finite()) {
                        return Err(format!("near-Clifford {name} requires finite coordinates"));
                    }
                } else if !args.is_empty() {
                    return Err(format!("near-Clifford {name} takes no arguments"));
                }
                if pair || noise_pair {
                    if !targets.len().is_multiple_of(2) {
                        return Err(format!("near-Clifford {name} requires qubit pairs"));
                    }
                    for targets in targets.chunks_exact(2) {
                        let second = match targets[1] {
                            StimTarget::Qubit(q) => q,
                            _ => {
                                return Err(format!(
                                    "near-Clifford {name} requires a qubit as second target"
                                ));
                            }
                        };
                        *max_qubit =
                            Some(max_qubit.map_or(second, |previous| previous.max(second)));
                        match targets[0] {
                            StimTarget::Qubit(first) => {
                                if first == second {
                                    return Err(format!(
                                        "near-Clifford {name} requires distinct qubits"
                                    ));
                                }
                                *max_qubit =
                                    Some(max_qubit.map_or(first, |previous| previous.max(first)));
                            }
                            StimTarget::Rec(offset) if pair && gate != "SWAP" && offset < 0 => {
                                validate_near_record(offset, *records)?;
                            }
                            StimTarget::Sweep(_) if pair && gate != "SWAP" => {}
                            _ => {
                                return Err(format!(
                                    "near-Clifford {name} requires qubit pairs or supported feedback"
                                ));
                            }
                        }
                    }
                } else if matches!(gate, "DETECTOR" | "OBSERVABLE_INCLUDE") {
                    for target in targets {
                        let StimTarget::Rec(offset) = target else {
                            return Err(format!(
                                "near-Clifford {name} requires negative rec targets"
                            ));
                        };
                        validate_near_record(*offset, *records)?;
                    }
                } else if matches!(gate, "SHIFT_COORDS" | "TICK") {
                    if !targets.is_empty() {
                        return Err(format!("near-Clifford {name} takes no targets"));
                    }
                } else {
                    if matches!(
                        gate,
                        "T" | "T_DAG" | "X_ERROR" | "Y_ERROR" | "Z_ERROR" | "DEPOLARIZE1"
                    ) && targets.is_empty()
                    {
                        return Err(format!("near-Clifford {name} requires a qubit target"));
                    }
                    for target in targets {
                        let q = match target {
                            StimTarget::Qubit(q) => *q,
                            StimTarget::QubitInv(q) if measure => *q,
                            _ => {
                                return Err(format!("near-Clifford {name} requires qubit targets"));
                            }
                        };
                        *max_qubit = Some(max_qubit.map_or(q, |previous| previous.max(q)));
                    }
                    if measure {
                        *records =
                            records
                                .checked_add(u64::try_from(targets.len()).map_err(
                                    |_| "near-Clifford measurement record count overflow",
                                )?)
                                .ok_or("near-Clifford measurement record count overflow")?;
                    }
                }
            }
        }
    }
    Ok(())
}

fn validate_near_record(offset: i32, records: u64) -> Result<(), String> {
    if offset >= 0 || u64::from(offset.unsigned_abs()) > records {
        return Err("near-Clifford rec out of range".into());
    }
    Ok(())
}

fn run_near_block(
    instructions: &[StimInstr],
    state: &mut ActiveState,
    measurements: &mut Vec<bool>,
    detectors: &mut Vec<bool>,
    observables: &mut Vec<(u32, bool)>,
    sweep_bits: &[bool],
    rng: &mut impl Rng,
) -> Result<(), String> {
    for instruction in instructions {
        match instruction {
            StimInstr::Repeat { count, body } => {
                for _ in 0..*count {
                    run_near_block(
                        body,
                        state,
                        measurements,
                        detectors,
                        observables,
                        sweep_bits,
                        rng,
                    )?;
                }
            }
            StimInstr::Op {
                name,
                args,
                targets,
                ..
            } => {
                if matches!(
                    name.as_str(),
                    "CX" | "CNOT" | "ZCX" | "CY" | "ZCY" | "CZ" | "ZCZ" | "SWAP"
                ) {
                    for pair in targets.chunks_exact(2) {
                        let b = pair[1].qubit_index().unwrap() as usize;
                        match pair[0] {
                            StimTarget::Qubit(a) => apply_near_pair(state, name, a as usize, b)?,
                            StimTarget::Rec(offset) => {
                                if near_record(measurements, offset)? {
                                    apply_near_feedback(state, name, b)?;
                                }
                            }
                            StimTarget::Sweep(k) => {
                                if sweep_bits.get(k as usize).copied().unwrap_or(false) {
                                    apply_near_feedback(state, name, b)?;
                                }
                            }
                            _ => unreachable!("validated near-Clifford pair target"),
                        }
                    }
                    continue;
                }
                if name == "DEPOLARIZE2" {
                    for pair in targets.chunks_exact(2) {
                        if near_noise_occurs(args[0], rng) {
                            let branch = rng.gen_range(1..16);
                            apply_near_pauli(
                                state,
                                pair[0].qubit_index().unwrap() as usize,
                                branch / 4,
                            )?;
                            apply_near_pauli(
                                state,
                                pair[1].qubit_index().unwrap() as usize,
                                branch % 4,
                            )?;
                        }
                    }
                    continue;
                }
                if matches!(name.as_str(), "DETECTOR" | "OBSERVABLE_INCLUDE") {
                    let mut parity = false;
                    for target in targets {
                        let StimTarget::Rec(offset) = target else {
                            unreachable!("validated record target")
                        };
                        parity ^= near_record(measurements, *offset)?;
                    }
                    if name == "DETECTOR" {
                        detectors.push(parity);
                    } else {
                        observables.push((args[0] as u32, parity));
                    }
                    continue;
                }
                if matches!(name.as_str(), "TICK" | "QUBIT_COORDS" | "SHIFT_COORDS") {
                    continue;
                }
                for target in targets {
                    let q = target.qubit_index().unwrap() as usize;
                    match name.as_str() {
                        "I" => {}
                        "H" => state.apply_clifford(CliffordGate::H(q))?,
                        "S" | "SQRT_Z" => state.apply_clifford(CliffordGate::S(q))?,
                        "S_DAG" | "SQRT_Z_DAG" => state.apply_clifford(CliffordGate::SDag(q))?,
                        "X" => state.apply_clifford(CliffordGate::X(q))?,
                        "Y" => state.apply_clifford(CliffordGate::Y(q))?,
                        "Z" => state.apply_clifford(CliffordGate::Z(q))?,
                        "T" => state.t(q)?,
                        "T_DAG" => state.t_dag(q)?,
                        "X_ERROR" | "Y_ERROR" | "Z_ERROR" | "DEPOLARIZE1" => {
                            if near_noise_occurs(args[0], rng) {
                                let branch = match name.as_str() {
                                    "X_ERROR" => 1,
                                    "Y_ERROR" => 2,
                                    "Z_ERROR" => 3,
                                    _ => rng.gen_range(1..4),
                                };
                                apply_near_pauli(state, q, branch)?;
                            }
                        }
                        "R" | "RZ" | "RX" | "RY" => {
                            let basis = match name.as_str() {
                                "RX" => MeasurementBasis::X,
                                "RY" => MeasurementBasis::Y,
                                _ => MeasurementBasis::Z,
                            };
                            state.reset(q, basis, rng)?;
                        }
                        "M" | "MZ" | "MX" | "MY" => {
                            let basis = match name.as_str() {
                                "MX" => MeasurementBasis::X,
                                "MY" => MeasurementBasis::Y,
                                _ => MeasurementBasis::Z,
                            };
                            let mut result = state.measure(q, basis, rng)?;
                            state.retire_fixed_axes();
                            result ^= matches!(target, StimTarget::QubitInv(_));
                            measurements.push(result);
                        }
                        "MR" | "MRZ" | "MRX" | "MRY" => {
                            let basis = match name.as_str() {
                                "MRX" => MeasurementBasis::X,
                                "MRY" => MeasurementBasis::Y,
                                _ => MeasurementBasis::Z,
                            };
                            let mut result = state.measure_reset(q, basis, rng)?;
                            result ^= matches!(target, StimTarget::QubitInv(_));
                            measurements.push(result);
                        }
                        _ => unreachable!("validated near-Clifford operation"),
                    }
                }
            }
        }
    }
    Ok(())
}

fn near_record(measurements: &[bool], offset: i32) -> Result<bool, String> {
    let distance =
        usize::try_from(offset.unsigned_abs()).map_err(|_| "near-Clifford rec out of range")?;
    if offset >= 0 || distance == 0 || distance > measurements.len() {
        return Err("near-Clifford rec out of range".into());
    }
    Ok(measurements[measurements.len() - distance])
}

fn near_noise_occurs(probability: f64, rng: &mut impl Rng) -> bool {
    probability >= 1.0 || (probability > 0.0 && rng.r#gen::<f64>() < probability)
}

fn apply_near_pauli(state: &mut ActiveState, q: usize, branch: usize) -> Result<(), String> {
    let gate = match branch {
        0 => return Ok(()),
        1 => CliffordGate::X(q),
        2 => CliffordGate::Y(q),
        3 => CliffordGate::Z(q),
        _ => unreachable!("validated Pauli branch"),
    };
    state.apply_clifford(gate)
}

fn apply_near_feedback(state: &mut ActiveState, name: &str, target: usize) -> Result<(), String> {
    let branch = match name {
        "CX" | "CNOT" | "ZCX" => 1,
        "CY" | "ZCY" => 2,
        "CZ" | "ZCZ" => 3,
        _ => unreachable!("validated near-Clifford feedback"),
    };
    apply_near_pauli(state, target, branch)
}

fn apply_near_pair(state: &mut ActiveState, name: &str, a: usize, b: usize) -> Result<(), String> {
    match name {
        "CX" | "CNOT" | "ZCX" => state.apply_clifford(CliffordGate::CX(a, b)),
        "CZ" | "ZCZ" => state.apply_clifford(CliffordGate::CZ(a, b)),
        "SWAP" => state.apply_clifford(CliffordGate::Swap(a, b)),
        "CY" | "ZCY" => {
            state.apply_clifford(CliffordGate::SDag(b))?;
            state.apply_clifford(CliffordGate::CX(a, b))?;
            state.apply_clifford(CliffordGate::S(b))
        }
        _ => unreachable!("validated near-Clifford pair gate"),
    }
}
