[package]
name = "rstim"
version = "0.1.1"
edition = "2024"
license.workspace = true

[features]
benchmark-telemetry = []

[dependencies]
rand = "0.8"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
libc = "0.2"
qec-code = { path = "../qec-code" }
zstd = "0.13"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
