import { test, expect } from '@playwright/test';

test('atom-loss evidence exposes three real figures and downloadable measurements', async ({ page }) => {
  await page.goto('/atom-loss/#atom-loss-results');
  const figures = page.locator('.loss-result-figure');
  await expect(figures).toHaveCount(3);
  for (const figure of await figures.all()) {
    await figure.scrollIntoViewIfNeeded();
    await expect.poll(() => figure.locator('img').evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
    await expect(figure.locator('figcaption')).toContainText(/shots|Distance/);
    const href = await figure.locator('a').getAttribute('href');
    const response = await page.request.get(new URL(href, page.url()).href);
    expect(response.ok()).toBe(true);
    expect(await response.text()).toContain('<svg');
  }
  const mainSampling = await (await page.request.get('/data/atom-loss/sampling-throughput.svg')).text();
  expect(mainSampling).toContain('RustQEC loss-visible sampling');
  expect(mainSampling).not.toContain('Stim');
  await page.locator('.loss-reference-cost summary').click();
  const reference = page.locator('.loss-reference-figure img');
  await reference.scrollIntoViewIfNeeded();
  await expect.poll(() => reference.evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
  await expect(page.locator('.loss-reference-figure figcaption')).toContainText('no speedup ratio');
  const timing = page.locator('.loss-timing-figure img');
  await timing.scrollIntoViewIfNeeded();
  await expect.poll(() => timing.evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
  await expect(page.locator('.loss-timing-figure figcaption')).toContainText('178.66 and 144.01');
  const timingCsv = await (await page.request.get('/data/atom-loss/timing-sweep.csv')).text();
  expect(timingCsv.trim().split('\n')).toHaveLength(136);
  const samplingCheck = await (await page.request.get('/data/atom-loss/correctness.json')).json();
  expect(samplingCheck.analytic_noise_controls.distribution_probes.cases).toHaveLength(26);
  expect(samplingCheck.analytic_noise_controls.distribution_probes.channel_replacement_mutations.DEPOLARIZE2_ix_only.rejected).toBe(true);
  await page.locator('.loss-full-sweep summary').click();
  const full = page.locator('.loss-full-figure img');
  await full.scrollIntoViewIfNeeded();
  await expect.poll(() => full.evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
  await expect(page.locator('.loss-full-figure figcaption')).toContainText('0.000599');
  const stages = page.locator('.loss-stage-figure img');
  await stages.scrollIntoViewIfNeeded();
  await expect.poll(() => stages.evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
  await expect(page.locator('.loss-stage-figure figcaption')).toContainText('not establish a matching-kernel');
  const chain = await (await page.request.get('/data/atom-loss/chain-correctness.json')).json();
  expect(chain.status).toBe('PASS');
  expect(chain.compiler_output_mutations_rejected).toEqual({ pauli_weight: true, loss_candidate: true });
  await page.locator('.loss-evidence-downloads summary').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download result table (CSV)' }).click();
  expect((await downloadPromise).suggestedFilename()).toBe('summary.csv');
  const archiveDownload = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download all 16 corpora and 150 prediction files (ZIP)' }).click();
  expect((await archiveDownload).suggestedFilename()).toBe('shot-data-v1.zip');
  const data = await (await page.request.get('/data/atom-loss/decoding.json')).json();
  expect(data).toHaveLength(15);
  expect(data.every(row => row.shots === 5000)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
});
