#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator


REPO_ROOT = Path(__file__).resolve().parents[1]
CHECKER = REPO_ROOT / "tools" / "check_agent_entry.py"
FIXTURE_PACKAGES = ("alpha", "beta")


def write_fixture_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


class AgentEntryCheckerTest(unittest.TestCase):
    def run_checker(self, repo_root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(CHECKER), "--repo-root", str(repo_root)],
            cwd=REPO_ROOT,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

    @contextmanager
    def temporary_fixture(self) -> Iterator[Path]:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary) / "repo"
            write_fixture_file(
                root / "Cargo.toml",
                "[workspace]\nmembers = [\"alpha\", \"beta\"]\nresolver = \"3\"\n",
            )
            write_fixture_file(
                root / "Cargo.lock",
                "# This file is automatically @generated by Cargo.\nversion = 4\n\n"
                "[[package]]\nname = \"alpha\"\nversion = \"0.1.0\"\n\n"
                "[[package]]\nname = \"beta\"\nversion = \"0.1.0\"\n",
            )
            write_fixture_file(
                root / "AGENTS.md",
                "# Agent Instructions\n\nRead the [repository guide](.AGENTS/AGENTS.md).\n",
            )
            write_fixture_file(
                root / ".AGENTS" / "AGENTS.md",
                "# Repository Guidelines\n\n"
                "## Current Workspace Members\n\n"
                "- `alpha` — `alpha/`\n"
                "- `beta` — `beta/`\n\n"
                "## Agent Rules\n\n"
                "Use the [QP101-ZY maintenance rule](rules/QP101-ZY.md).\n",
            )
            write_fixture_file(root / ".AGENTS" / "rules" / "QP101-ZY.md", "# Fixture rule\n")
            for package in FIXTURE_PACKAGES:
                write_fixture_file(
                    root / package / "Cargo.toml",
                    f"[package]\nname = \"{package}\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
                )
                write_fixture_file(root / package / "src" / "lib.rs", "\n")
            yield root

    def test_live_entry_passes_with_current_metadata_count(self) -> None:
        result = self.run_checker(REPO_ROOT)
        metadata = subprocess.run(
            ["cargo", "metadata", "--locked", "--no-deps", "--format-version", "1"],
            cwd=REPO_ROOT,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
        )
        count = len(json.loads(metadata.stdout)["workspace_members"])

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, f"PASS agent entry members={count}\n")
        self.assertEqual(result.stderr, "")

    def test_fixture_passes_with_two_packages(self) -> None:
        with self.temporary_fixture() as root:
            result = self.run_checker(root)

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, "PASS agent entry members=2\n")

    def test_missing_root_routing_target_fails_with_path(self) -> None:
        with self.temporary_fixture() as root:
            (root / ".AGENTS" / "AGENTS.md").unlink()

            result = self.run_checker(root)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("missing local link target: .AGENTS/AGENTS.md", result.stderr)

    def test_missing_workspace_member_fails_with_name(self) -> None:
        with self.temporary_fixture() as root:
            guide = root / ".AGENTS" / "AGENTS.md"
            guide.write_text(
                guide.read_text(encoding="utf-8").replace("- `alpha` — `alpha/`\n", ""),
                encoding="utf-8",
            )

            result = self.run_checker(root)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("missing workspace members: alpha", result.stderr)

    def test_empty_markdown_link_reports_a_validation_error(self) -> None:
        with self.temporary_fixture() as root:
            (root / "AGENTS.md").write_text("# Agent Instructions\n\n[empty]()\n", encoding="utf-8")

            result = self.run_checker(root)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("malformed empty Markdown link", result.stderr)


if __name__ == "__main__":
    unittest.main()
