#!/usr/bin/env python3
from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator


REPO_ROOT = Path(__file__).resolve().parents[1]
CHECKER = REPO_ROOT / "tools" / "check_rmatching_readme.py"


def write_fixture_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


class RmatchingReadmeCheckerTest(unittest.TestCase):
    def run_checker(self, repo_root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(CHECKER), "--repo-root", str(repo_root)],
            cwd=REPO_ROOT,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

    @contextmanager
    def temporary_fixture(self) -> Iterator[Path]:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary) / "repo"
            write_fixture_file(
                root / "Cargo.toml",
                "[workspace]\nmembers = [\"rmatching\"]\nresolver = \"3\"\n",
            )
            write_fixture_file(
                root / "Cargo.lock",
                "# This file is automatically @generated by Cargo.\nversion = 4\n\n"
                "[[package]]\nname = \"rmatching\"\nversion = \"0.1.0\"\n",
            )
            write_fixture_file(
                root / "rmatching" / "Cargo.toml",
                "[package]\nname = \"rmatching\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\n"
                "[features]\nbench = []\n",
            )
            write_fixture_file(
                root / "rmatching" / "src" / "lib.rs",
                "pub struct Matching;\n\n"
                "impl Matching {\n"
                "    pub fn from_dem(dem: &str) -> Result<Self, &'static str> {\n"
                "        if dem.contains(\"D0 D1 D2\") { Err(\"graphlike DEM required\") } else { Ok(Self) }\n"
                "    }\n"
                "    pub fn decode(&mut self, syndrome: &[u8]) -> Vec<u8> {\n"
                "        if syndrome == [1, 1] { vec![1] } else { vec![] }\n"
                "    }\n"
                "}\n",
            )
            write_fixture_file(
                root / "rmatching" / "README.md",
                "# rmatching\n\n"
                "## Cargo Features\n\n"
                "- `bench`: enables benchmark binaries.\n\n"
                "## Quick Start\n\n"
                "```rust\n"
                "use rmatching::Matching;\n\n"
                "fn main() {\n"
                "    let mut matching = Matching::from_dem(\"error(0.1) D0 D1 L0\\n\").unwrap();\n"
                "    assert_eq!(matching.decode(&[1, 1]), vec![1]);\n"
                "    assert!(Matching::from_dem(\"error(0.1) D0 D1 D2\\n\").is_err());\n"
                "}\n"
                "```\n\n"
                "## Workspace Links\n\n"
                "See the [showcase](../docs/showcases/benchmark-evidence.md) and [CI](../.github/workflows/ci.yml).\n",
            )
            write_fixture_file(root / "docs" / "showcases" / "benchmark-evidence.md", "# Fixture showcase\n")
            write_fixture_file(root / ".github" / "workflows" / "ci.yml", "name: fixture\n")
            yield root

    def test_live_readme_passes(self) -> None:
        result = self.run_checker(REPO_ROOT)

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, "PASS rmatching README\n")

    def test_fixture_rejects_nonexistent_advertised_feature(self) -> None:
        with self.temporary_fixture() as root:
            readme = root / "rmatching" / "README.md"
            readme.write_text(
                readme.read_text(encoding="utf-8").replace(
                    "- `bench`: enables benchmark binaries.\n",
                    "- `bench`: enables benchmark binaries.\n- `rsinter`: enables integration.\n",
                ),
                encoding="utf-8",
            )
            result = self.run_checker(root)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("advertised Cargo features do not match metadata: extra=rsinter", result.stderr)

    def test_fixture_rejects_broken_showcase_link(self) -> None:
        with self.temporary_fixture() as root:
            readme = root / "rmatching" / "README.md"
            readme.write_text(
                readme.read_text(encoding="utf-8").replace(
                    "../docs/showcases/benchmark-evidence.md",
                    "../docs/showcases/missing.md",
                ),
                encoding="utf-8",
            )
            result = self.run_checker(root)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("missing local README link target: docs/showcases/missing.md", result.stderr)


if __name__ == "__main__":
    unittest.main()
